```
from autogluon.tabular import TabularDataset, TabularPredictor
data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
train_data.head()
```

In [10]:
from autogluon.tabular import TabularDataset, TabularPredictor
data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
train_data.head()

Loaded data from: https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/train.csv | Columns = 19 / 19 | Rows = 10000 -> 10000

,Unnamed: 0,chern_simons,cusp_volume,hyperbolic_adjoint_torsion_degree,hyperbolic_torsion_degree,injectivity_radius,longitudinal_translation,meridinal_translation_imag,meridinal_translation_real,short_geodesic_imag_part,short_geodesic_real_part,Symmetry_0,Symmetry_D3,Symmetry_D4,Symmetry_D6,Symmetry_D8,Symmetry_Z/2 + Z/2,volume,signature
0,70746,0.090530,12.226322,0,10,0.507756,10.685555,1.144192,-0.519157,-2.760601,1.015512,0.0,0.0,0.0,0.0,0.0,1.0,11.393225,-2
1,240827,0.232453,13.800773,0,14,0.413645,10.453156,1.320249,-0.158522,-3.013258,0.827289,0.0,0.0,0.0,0.0,0.0,1.0,12.742782,0
2,155659,-0.144099,14.761030,0,14,0.436928,13.405199,1.101142,0.768894,2.233106,0.873856,0.0,0.0,0.0,0.0,0.0,0.0,15.236505,2
3,239963,-0.171668,13.738019,0,22,0.249481,27.819496,0.493827,-1.188718,-2.042771,0.498961,0.0,0.0,0.0,0.0,0.0,0.0,17.279890,-8
4,90504,0.235188,15.896359,0,10,0.389329,15.330971,1.036879,0.722828,-3.056138,0.778658,0.0,0.0,0.0,0.0,0.0,0.0,16.749298,4

In [11]:
save_path = "./model/"
label = 'signature'
predictor = TabularPredictor(label="signature", path=save_path)

In [1]:
# from autogluon.tabular import TabularDataset, TabularPredictor
# train_data = TabularDataset('diamonds.csv')
# save_path = "./model/"
# predictor = TabularPredictor(label="Price", path=save_path)

Warning: path already exists! This predictor may overwrite an existing predictor! path="./model/"

In [12]:
predictor.fit(
    train_data=train_data,
    ag_args_fit={
        'num_cpus': 4, 
        'num_gpus': 1
    },  # 啟用 GPU
    # 可以限制時間以快速驗證
    time_limit=300  # 5分鐘
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.9
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #156~18.04.1-Ubuntu SMP Wed Jan 25 15:56:22 UTC 2023
CPU Count:          64
Pytorch Version:    2.6.0
CUDA Version:       12.6
GPU Memory:         GPU 0: 22.35/22.37 GB | GPU 1: 22.37/22.37 GB
Total GPU Memory:   Free: 44.72 GB, Allocated: 0.02 GB, Total: 44.74 GB
GPU Count:          2
Memory Avail:       89.62 GB / 125.52 GB (71.4%)
Disk Space Avail:   442.73 GB / 1475.38 GB (30.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/home/sagemaker-user/src/model"
Train Data Rows:    10000
Train Data Columns: 18
Label Column:       signature
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == int, but few unique label-values observed).
	First 10 (of 13) unique label values:  [-2, 0, 2, -8, 4, -4, -6, 8, 6, 10]
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Warning: Some classes in the training set have fewer than 10 examples. AutoGluon will only keep 9 out of 13 classes for training and will not try to predict the rare classes. To keep more classes, increase the number of datapoints from these rare classes in the training data or reduce label_count_threshold.
Fraction of data from classes with at least 10 examples that will be kept for training models: 0.9984
Train Data Class Count: 9
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    91767.95 MB
	Train Data (Original)  Memory Usage: 1.37 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['Symmetry_D8']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])   :  3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 9 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])       : 3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
		('int', ['bool']) : 5 | ['Symmetry_0', 'Symmetry_D3', 'Symmetry_D4', 'Symmetry_D6', 'Symmetry_Z/2 + Z/2']
	0.2s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 0.96 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.2s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 8985, Val Rows: 999
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 299.80s of the 299.80s of remaining time.
	Fitting with cpus=4, gpus=1, mem=0.0/89.6 GB
	0.9429	 = Validation score   (accuracy)
	10.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 289.69s of the 289.69s of remaining time.
	Fitting with cpus=4, gpus=1, mem=0.1/89.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.9459	 = Validation score   (accuracy)
	6.93s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 282.59s of the 282.59s of remaining time.
	Fitting with cpus=4, gpus=1, mem=0.1/89.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.956	 = Validation score   (accuracy)
	5.21s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 277.28s of the 277.28s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.4/89.6 GB
	0.9449	 = Validation score   (accuracy)
	2.88s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 274.01s of the 274.01s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.4/89.1 GB
	0.9499	 = Validation score   (accuracy)
	2.32s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 271.35s of the 271.35s of remaining time.
	Fitting with cpus=4, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.9309	 = Validation score   (accuracy)
	5.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 265.90s of the 265.90s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.4/89.0 GB
	0.9469	 = Validation score   (accuracy)
	2.39s	 = Training   runtime
	0.25s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 263.05s of the 263.04s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.4/89.0 GB
	0.9429	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.21s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 260.94s of the 260.94s of remaining time.
	Fitting with cpus=4, gpus=1
	0.957	 = Validation score   (accuracy)
	9.15s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 251.66s of the 251.66s of remaining time.
	Fitting with cpus=4, gpus=1, mem=0.0/88.9 GB
/opt/conda/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9479	 = Validation score   (accuracy)
	58.35s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 193.27s of the 193.27s of remaining time.
	Fitting with cpus=4, gpus=1, mem=0.6/88.9 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.9499	 = Validation score   (accuracy)
	10.81s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.80s of the 182.08s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=64, gpus=0, mem=0.0/88.9 GB
	Ensemble Weights: {'XGBoost': 0.3, 'NeuralNetFastAI': 0.2, 'RandomForestEntr': 0.2, 'CatBoost': 0.1, 'ExtraTreesGini': 0.1, 'NeuralNetTorch': 0.1}
	0.964	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 118.06s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1783.8 rows/s (999 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/sagemaker-user/src/model")

In [13]:
predictor.leaderboard(display=True)

                  model  score_val eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   WeightedEnsemble_L2   0.963964    accuracy       0.560039  87.794038                0.000855           0.098016            2       True         12
1               XGBoost   0.956957    accuracy       0.055456   9.147931                0.055456           9.147931            1       True          9
2              LightGBM   0.955956    accuracy       0.032244   5.213009                0.032244           5.213009            1       True          3
3         LightGBMLarge   0.949950    accuracy       0.067039  10.814346                0.067039          10.814346            1       True         11
4      RandomForestEntr   0.949950    accuracy       0.217179   2.319187                0.217179           2.319187            1       True          5
5        NeuralNetTorch   0.947948    accuracy       0.010842  58.354763                0.010842          58.354763            1       True         10
6        ExtraTreesGini   0.946947    accuracy       0.245860   2.389113                0.245860           2.389113            1       True          7
7            LightGBMXT   0.945946    accuracy       0.048348   6.927318                0.048348           6.927318            1       True          2
8      RandomForestGini   0.944945    accuracy       0.215751   2.883640                0.215751           2.883640            1       True          4
9       NeuralNetFastAI   0.942943    accuracy       0.013104  10.071656                0.013104          10.071656            1       True          1
10       ExtraTreesEntr   0.942943    accuracy       0.206372   1.721226                0.206372           1.721226            1       True          8
11             CatBoost   0.930931    accuracy       0.016743   5.413374                0.016743           5.413374            1       True          6

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.963964,accuracy,0.560039,87.794038,0.000855,0.098016,2,True,12
1,XGBoost,0.956957,accuracy,0.055456,9.147931,0.055456,9.147931,1,True,9
2,LightGBM,0.955956,accuracy,0.032244,5.213009,0.032244,5.213009,1,True,3
3,LightGBMLarge,0.949950,accuracy,0.067039,10.814346,0.067039,10.814346,1,True,11
4,RandomForestEntr,0.949950,accuracy,0.217179,2.319187,0.217179,2.319187,1,True,5
5,NeuralNetTorch,0.947948,accuracy,0.010842,58.354763,0.010842,58.354763,1,True,10
6,ExtraTreesGini,0.946947,accuracy,0.245860,2.389113,0.245860,2.389113,1,True,7
7,LightGBMXT,0.945946,accuracy,0.048348,6.927318,0.048348,6.927318,1,True,2
8,RandomForestGini,0.944945,accuracy,0.215751,2.883640,0.215751,2.883640,1,True,4
9,NeuralNetFastAI,0.942943,accuracy,0.013104,10.071656,0.013104,10.071656,1,True,1
10,ExtraTreesEntr,0.942943,accuracy,0.206372,1.721226,0.206372,1.721226,1,True,8
11,CatBoost,0.930931,accuracy,0.016743,5.413374,0.016743,5.413374,1,True,6

In [14]:
aaa = TabularPredictor.load(save_path)

In [15]:
test_sample = train_data.head(5)
test_sample

,Unnamed: 0,chern_simons,cusp_volume,hyperbolic_adjoint_torsion_degree,hyperbolic_torsion_degree,injectivity_radius,longitudinal_translation,meridinal_translation_imag,meridinal_translation_real,short_geodesic_imag_part,short_geodesic_real_part,Symmetry_0,Symmetry_D3,Symmetry_D4,Symmetry_D6,Symmetry_D8,Symmetry_Z/2 + Z/2,volume,signature
0,70746,0.090530,12.226322,0,10,0.507756,10.685555,1.144192,-0.519157,-2.760601,1.015512,0.0,0.0,0.0,0.0,0.0,1.0,11.393225,-2
1,240827,0.232453,13.800773,0,14,0.413645,10.453156,1.320249,-0.158522,-3.013258,0.827289,0.0,0.0,0.0,0.0,0.0,1.0,12.742782,0
2,155659,-0.144099,14.761030,0,14,0.436928,13.405199,1.101142,0.768894,2.233106,0.873856,0.0,0.0,0.0,0.0,0.0,0.0,15.236505,2
3,239963,-0.171668,13.738019,0,22,0.249481,27.819496,0.493827,-1.188718,-2.042771,0.498961,0.0,0.0,0.0,0.0,0.0,0.0,17.279890,-8
4,90504,0.235188,15.896359,0,10,0.389329,15.330971,1.036879,0.722828,-3.056138,0.778658,0.0,0.0,0.0,0.0,0.0,0.0,16.749298,4

In [16]:
y_pred = aaa.predict(test_sample)
y_pred

0   -2
1    0
2    2
3   -8
4    4
Name: signature, dtype: int64

In [9]:
# !pip install -q bokeh==2.0.1 jinja2==2.11.3  markupsafe==2.0.1

# import numpy as np

# 相容性修補：修正舊版套件對 np.bool8 的相依性
# if not hasattr(np, 'bool8'):
#     np.bool8 = np.bool_  # 或 np.bool

# from bokeh.plotting import output_notebook
# output_notebook()  # 注意：必須在任何繪圖操作前呼叫


predictor.fit_summary(show_plot=False)

*** Summary of fit() ***
Estimated performance of each model:
                 model    score_val              eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2 -1086.796253  root_mean_squared_error       0.107263  18.628219                0.000488           0.007940            2       True         10
1             LightGBM -1128.459337  root_mean_squared_error       0.008887   0.579900                0.008887           0.579900            1       True          2
2           LightGBMXT -1150.948560  root_mean_squared_error       0.045481   3.565373                0.045481           3.565373            1       True          1
3              XGBoost -1220.920884  root_mean_squared_error       0.012325   2.314968                0.012325           2.314968            1       True          7
4      NeuralNetFastAI -1250.137551  root_mean_squared_error       0.019769   5.385792                0.019769           5.385792            1       True          6
5        LightGBMLarge -1256.747353  root_mean_squared_error       0.004776   0.682432                0.004776           0.682432            1       True          9
6       NeuralNetTorch -1302.050880  root_mean_squared_error       0.006584  15.244323                0.006584          15.244323            1       True          8
7        ExtraTreesMSE -1325.327192  root_mean_squared_error       0.078979   0.481087                0.078979           0.481087            1       True          5
8             CatBoost -1428.340009  root_mean_squared_error       0.003082  22.289525                0.003082          22.289525            1       True          4
9      RandomForestMSE -1459.842120  root_mean_squared_error       0.078150   0.564665                0.078150           0.564665            1       True          3
Number of models trained: 10
Types of models trained:
{'XTModel', 'RFModel', 'NNFastAiTabularModel', 'CatBoostModel', 'LGBModel', 'WeightedEnsembleModel', 'TabularNeuralNetTorchModel', 'XGBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])  : 5 | ['Cut', 'Color', 'Clarity', 'Polish', 'Symmetry']
('float', [])     : 1 | ['Carat Weight']
('int', ['bool']) : 1 | ['Report']
*** End of fit() summary ***

/opt/conda/lib/python3.12/site-packages/autogluon/core/utils/plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"
  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"')

{'model_types': {'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestMSE': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesMSE': 'XTModel',
  'NeuralNetFastAI': 'NNFastAiTabularModel',
  'XGBoost': 'XGBoostModel',
  'NeuralNetTorch': 'TabularNeuralNetTorchModel',
  'LightGBMLarge': 'LGBModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'LightGBMXT': -1150.948559897322,
  'LightGBM': -1128.4593373697787,
  'RandomForestMSE': -1459.8421201063586,
  'CatBoost': -1428.3400087661694,
  'ExtraTreesMSE': -1325.327192220721,
  'NeuralNetFastAI': -1250.1375506873283,
  'XGBoost': -1220.9208842955504,
  'NeuralNetTorch': -1302.0508795278545,
  'LightGBMLarge': -1256.7473525317062,
  'WeightedEnsemble_L2': -1086.7962531680628},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestMSE': ['RandomForestMSE'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesMSE': ['ExtraTreesMSE'],
  'NeuralNetFastAI': ['NeuralNetFastAI'],
  'XGBoost': ['XGBoost'],
  'NeuralNetTorch': ['NeuralNetTorch'],
  'LightGBMLarge': ['LightGBMLarge'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'LightGBMXT': 3.5653727054595947,
  'LightGBM': 0.5799000263214111,
  'RandomForestMSE': 0.5646653175354004,
  'CatBoost': 22.289525032043457,
  'ExtraTreesMSE': 0.48108744621276855,
  'NeuralNetFastAI': 5.385792016983032,
  'XGBoost': 2.3149683475494385,
  'NeuralNetTorch': 15.244323492050171,
  'LightGBMLarge': 0.682431697845459,
  'WeightedEnsemble_L2': 0.007940053939819336},
 'model_pred_times': {'LightGBMXT': 0.045480966567993164,
  'LightGBM': 0.008887052536010742,
  'RandomForestMSE': 0.07815027236938477,
  'CatBoost': 0.0030815601348876953,
  'ExtraTreesMSE': 0.0789785385131836,
  'NeuralNetFastAI': 0.019768714904785156,
  'XGBoost': 0.012324810028076172,
  'NeuralNetTorch': 0.00658416748046875,
  'LightGBMLarge': 0.004776477813720703,
  'WeightedEnsemble_L2': 0.00048828125},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'LightGBMXT': {'learning_rate': 0.05,
   'extra_trees': True,
   'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'RMSE',
   'random_seed': 0},
  'ExtraTreesMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'reg:squarederror',
   'booster': 'gbtree',
   'seed': 0},
  'NeuralNetTorch': {'num_epochs': 1000,
   'epochs_wo_improve': None,
   'activation': 'relu',
   'embedding_size_factor': 1.0,
   'embed_exponent': 0.56,
   'max_embedding_dim': 100,
   'y_range': None,
   'y_range_extend': 0.05,
   'dropout_prob': 0.1,
   'optimizer': 'adam',
   'learning_rate': 0.0003,
   'weight_decay': 1e-06,
   'proc.embed_min_categories': 4,
   'proc.impute_strategy': 'median',
   'proc.max_category_levels': 100,
   'proc.skew_threshold': 0.99,
   'use_ngram_features': False,
   'num_layers': 4,
   'hidden_size': 128,
   'max_batch_size': 512,
   'use_batchnorm': False,
   'loss_function': 'auto',
   'seed_value': 0},
  'LightGBMLarge': {'learning_rate': 0.03,
   'num_leaves': 128,
   'feature_fraction': 0.9,
   'min_data_in_leaf': 3,
   'seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                  model    score_val              eval_metric  pred_time_val  \
 0  WeightedEnsemble_L2 -1086.796253  root_mean_squared_error       0.107263
 1             LightGBM -1128.459337  root_mean_squared_error       0.008887
 2           LightGBMXT -1150.948560  root_mean_squared_error       0.045481
 3              XGBoost -1220.920884  root_mean_squared_error       0.012325
 4      NeuralNetFastAI -1250.137551  root_mean_squared_error       0.019769
 5        LightGBMLarge -1256.747353  root_mean_squared_error       0.004776
 6       NeuralNetTorch -1302.050880  root_mean_squared_error       0.006584
 7        ExtraTreesMSE -1325.327192  root_mean_squared_error       0.078979
 8             CatBoost -1428.340009  root_mean_squared_error       0.003082
 9      RandomForestMSE -1459.842120  root_mean_squared_error       0.078150

     fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  18.628219                0.000488           0.007940            2
 1   0.579900                0.008887           0.579900            1
 2   3.565373                0.045481           3.565373            1
 3   2.314968                0.012325           2.314968            1
 4   5.385792                0.019769           5.385792            1
 5   0.682432                0.004776           0.682432            1
 6  15.244323                0.006584          15.244323            1
 7   0.481087                0.078979           0.481087            1
 8  22.289525                0.003082          22.289525            1
 9   0.564665                0.078150           0.564665            1

    can_infer  fit_order
 0       True         10
 1       True          2
 2       True          1
 3       True          7
 4       True          6
 5       True          9
 6       True          8
 7       True          5
 8       True          4
 9       True          3  }